FROM node:12.16.1

WORKDIR /
COPY package.json ./package.json
COPY ./src ./src
COPY ./public ./public
RUN npm install
RUN npm run build
COPY .env.staging .env
EXPOSE 8080

CMD [ "npm", "run", "startServer" ]