FROM node:12.16.1
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
# Install app dependencies
COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/
RUN npm install
# Bundle app source
COPY . /usr/src/app
COPY .env.production /usr/src/app/.env
RUN npm run build

CMD [ "npm", "start" ]