FROM node:12.16.1

WORKDIR /
COPY package.json ./package.json
COPY ./public ./public
COPY ./src ./src
COPY .env.staging .env
RUN npm install
RUN npm run build

CMD [ "npm", "run", "startServer" ]