const ORDERS = [{
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  paid_date: '',
  fullfilled_date: '',
  id: 1,
  is_paid: false,
  is_fullfilled: false,
  user: {
    id: 510244122,
    name: 'שם ארוך למשתמש',
    company: 'הפיראט האדום',
  },
  notes: '',
  delivery_address: {
    city: 'נתניה',
    address: 'רחוב הזלדים 52',
    zipcode: '251251',
    notes: '',
  },
  variations: [{
    catalog_id: 1,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 49.99,
    id: 2,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'בד קנווס סוג א',
  },
  {
    catalog_id: 2,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 59.99,
    id: 3,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'טוש ירוק זוהר',
  }],
}, {
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  paid_date: new Date().toISOString(),
  fullfilled_date: '',
  id: 2,
  is_paid: true,
  is_fullfilled: false,
  user: {
    id: 510236472,
    name: 'משתמש בדיקה',
    company: 'הפיראט האדום',
  },
  notes: '',
  delivery_address: {
    city: 'נתניה',
    address: 'רחוב הזלדים 52',
    zipcode: '251251',
    notes: '',
  },
  variations: [{
    catalog_id: 1,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 49.99,
    id: 2,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'בד קנווס סוג א',
  },
  {
    catalog_id: 2,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 59.99,
    id: 3,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'טוש ירוק זוהר',
  }],
}, {
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  paid_date: new Date().toISOString(),
  fullfilled_date: new Date().toISOString(),
  id: 3,
  is_paid: true,
  is_fullfilled: true,
  user: {
    id: 510244122,
    name: 'משתמש בדיקה',
    company: 'הפיראט האדום',
  },
  notes: '',
  delivery_address: {
    city: 'נתניה',
    address: 'רחוב הזלדים 52',
    zipcode: '251251',
    notes: '',
  },
  variations: [{
    catalog_id: 1,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 49.99,
    id: 2,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'בד קנווס סוג א',
  },
  {
    catalog_id: 2,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 59.99,
    id: 3,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'טוש ירוק זוהר',
  }],
}, {
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  paid_date: new Date().toISOString(),
  fullfilled_date: new Date().toISOString(),
  id: 3,
  is_paid: true,
  is_fullfilled: true,
  user: {
    id: 510244122,
    name: 'משתמש בדיקה',
    company: 'הפיראט האדום',
  },
  notes: '',
  delivery_address: {
    city: 'נתניה',
    address: 'רחוב הזלדים 52',
    zipcode: '251251',
    notes: '',
  },
  variations: [{
    catalog_id: 1,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 49.99,
    id: 2,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'בד קנווס סוג א',
  },
  {
    catalog_id: 2,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 59.99,
    id: 3,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_ordered: 2,
    title: 'טוש ירוק זוהר',
  }],
}];

export default ORDERS;
