const PRODUCTS = [{
  catalog_id: 1,
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  brand: 'מותג',
  description: 'תיאור המוצר',
  id: 1,
  labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
  title: 'בד קנווס סוג א',
  variations: [{
    catalog_id: 1,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    price: 49.99,
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 2,
    is_available: false,
    labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
    product_id: 1,
    quantity_num_in_unit: 2,
    title: 'בד קנווס סוג א',
    unit_sale_precentage: 10,
  }],
},
{
  catalog_id: 2,
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  brand: 'מותג שני',
  description: 'תיאור המוצר',
  id: 2,
  labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
  title: 'טוש זוהר בצבעים',
  variations: [{
    catalog_id: 2,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 1,
    price: 59.99,
    is_available: true,
    labels: [],
    product_id: 2,
    quantity_num_in_unit: 2,
    title: 'טוש אדום זוהר',
    unit_sale_precentage: 10,
  }, {
    catalog_id: 2,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 2,
    price: 59.99,
    is_available: true,
    labels: [],
    product_id: 2,
    quantity_num_in_unit: 0,
    title: 'טוש צהוב זוהר',
    unit_sale_precentage: 10,
  },
  {
    catalog_id: 2,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 3,
    price: 59.99,
    is_available: true,
    labels: [],
    product_id: 2,
    quantity_num_in_unit: 5,
    title: 'טוש ירוק זוהר',
    unit_sale_precentage: 10,
  }],
},
{
  catalog_id: 3,
  created_utc: new Date().toISOString(),
  updated_utc: new Date().toISOString(),
  brand: 'מותג שלישי',
  description: 'תיאור המוצר',
  id: 3,
  labels: [{ type: 'label1', value: 'test' }, { type: 'label2', value: 'test2' }],
  title: 'צבעי גואש',
  variations: [{
    catalog_id: 3,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 1,
    price: 59.99,
    is_available: true,
    labels: [],
    product_id: 3,
    quantity_num_in_unit: 2,
    title: 'גואש סוג א אדום',
    unit_sale_precentage: 10,
  }, {
    catalog_id: 3,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 2,
    price: 59.99,
    is_available: true,
    labels: [],
    product_id: 3,
    quantity_num_in_unit: 0,
    title: 'גואש סוג א צהוב',
    unit_sale_precentage: 10,
  },
  {
    catalog_id: 3,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 3,
    price: 59.99,
    is_available: true,
    labels: [],
    product_id: 3,
    quantity_num_in_unit: 5,
    title: 'גואש סוג א כחול',
    unit_sale_precentage: 10,
  },
  {
    catalog_id: 3,
    availability_changed_utc: null,
    images: ['https://www.artdepot.co.il/15407-thickbox_default/מקרמה-נטוראל-3-גידים-במבחר-גוונים.jpg'],
    created_utc: new Date().toISOString(),
    updated_utc: new Date().toISOString(),
    oos_date: new Date().toISOString(),
    id: 3,
    price: 59.99,
    is_available: false,
    labels: [],
    product_id: 3,
    quantity_num_in_unit: 5,
    title: 'גואש סוג א סגול',
    unit_sale_precentage: 10,
  }],
}];

export default PRODUCTS;
